[[libbmp_vyu]]
arch = "x86_64"
git-tree-sha1 = "d7c2d6f452f259ef1396dcd42672eecc5c2c3335"
libc = "glibc"
os = "linux"

    [[libbmp_vyu.download]]
    sha256 = "1b470a5ed3acdd4a79b9c2b422e43c848ec7fb96f9510b1790917cf4937d26c2"
    url = "https://github.com/aelobdog/bmp_vyu_jll.jl/releases/download/libbmp_vyu-v0.1.2+0/libbmp_vyu.v0.1.2.x86_64-linux-gnu.tar.gz"
