# Autogenerated wrapper script for libbmp_vyu_jll for x86_64-linux-gnu
export libbmp_vyu

using Raylib_jll
JLLWrappers.@generate_wrapper_header("libbmp_vyu")
JLLWrappers.@declare_library_product(libbmp_vyu, "libbmp-vyu.so")
function __init__()
    JLLWrappers.@generate_init_header(Raylib_jll)
    JLLWrappers.@init_library_product(
        libbmp_vyu,
        "lib/libbmp-vyu.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
